version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "wisebits"
      POSTGRES_USER: "wisebits"
      POSTGRES_PASSWORD: "password"
    volumes:
        - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  nginx:
    image: nginx:latest
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/wisebit.nginx.conf
    links:
      - php
    ports:
      - "8080:8080"
  php:
    build: .
    links:
      - postgres
    ports:
      - "9000:9000"
    volumes:
      - ./:/usr/share/nginx/html